CREATE DATABASE RedNaJava;
USE RedNaJava;

CREATE TABLE CLIENTS(
	ID_CLIENT BIGINT PRIMARY KEY NOT NULL,
    COMPLETE_NAME VARCHAR(250) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PASS VARCHAR(50) NOT NULL,
    ROLE VARCHAR(1) NOT NULL DEFAULT 'C',
    TELEPHONE NUMERIC NULL
);

CREATE TABLE PRODUCTS(
	ID_PRODUCT INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    PRICE BIGINT NOT NULL,
    DESCRIPTION VARCHAR(300) NOT NULL,
    STOCK INT NOT NULL
);

CREATE TABLE PRODUCTS_ORDER(
	ID_ORDER INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ID_CLIENT BIGINT REFERENCES CLIENT(ID_CLIENT),
    ID_PRODUCT INT REFERENCES PRODUCTS(ID_PRODUCT),
    QUANTITY INT NOT NULL
);

/*DELIMITER //
CREATE PROCEDURE PRUEBA(IN ID_CLIENT BIGINT)
BEGIN
	SELECT * FROM CLIENT
    WHERE CLIENT.ID_CLIENT = ID_CLIENT;
END
//*/

USE RedNaJava;
select * from clients;
insert into clients values(1000203424, 'David Mendoza', 'abc@abc.com', '123456', 1, null)
insert into clients values(1040203424, 'Wilmer Garzon', 'abc@abc.com', '123456', 0, null)